theme: jekyll-theme-slate
title: Statistical Physics For Optimization and Learning
description :A Set of Lectures given at Duke in 2018 by Lenka Zdeborova and Florent Krzakala "Statistical Physics For Optimization and Learning"
